### ISSUE TITLE
Reflection error

### ISSUE THREAD

**Issue by rafi67000** [artemisac/artemis-minecraft-anticheat#3]
**Describe the bug**
if you launch server on some spigot forks with implemented TerminalConsoleAppender (for example paper 1.12.2 or pandaspigot 1.8) reflection throws error 

**To Reproduce**
1. launch spigot with terminalconsoleappender
2. enjoy errors
**Logs**
```
[15:03:41 INFO]: [ArtemisDev] Enabling Artemis v${project.version}
[15:03:41 ERROR]: Error occurred while enabling Artemis v${project.version} (Is it up to date?)
java.lang.IllegalStateException: Unable to find method getReader ([]).
        at cc.ghast.packet.reflections.Reflection.getTypedMethod(Reflection.java:252) ~[?:?]
        at cc.ghast.packet.reflections.Reflection.getMethod(Reflection.java:205) ~[?:?]
        at cc.ghast.packet.reflections.Reflection.getTypedMethod(Reflection.java:250) ~[?:?]
        at cc.ghast.packet.reflections.Reflection.getMethod(Reflection.java:205) ~[?:?]
        at ac.artemis.anticheat.bukkit.reflect.StandardBukkitReflection.<init>(StandardBukkitReflection.java:13) ~[?:?]
        at ac.artemis.anticheat.bukkit.BukkitArtemis.load(BukkitArtemis.java:67) ~[?:?]
        at ac.artemis.anticheat.ArtemisDev.onEnable(ArtemisDev.java:21) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[patched_1.8.8.jar:git-PandaSpigot-85]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) ~[patched_1.8.8.jar:git-PandaSpigot-85]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:454) ~[patched_1.8.8.jar:git-PandaSpigot-85]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:393) ~[patched_1.8.8.jar:git-PandaSpigot-85]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:352) ~[patched_1.8.8.jar:git-PandaSpigot-85]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:439) ~[patched_1.8.8.jar:git-PandaSpigot-85]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:403) ~[patched_1.8.8.jar:git-PandaSpigot-85]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java) ~[patched_1.8.8.jar:git-PandaSpigot-85]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:301) ~[patched_1.8.8.jar:git-PandaSpigot-85]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:603) ~[patched_1.8.8.jar:git-PandaSpigot-85]
        at net.minecraft.server.v1_8_R3.MinecraftServer.lambda$spin$0(MinecraftServer.java:133) ~[patched_1.8.8.jar:git-PandaSpigot-85]
        at java.lang.Thread.run(Thread.java:1589) [?:?]
[15:03:41 INFO]: [ArtemisDev] Disabling Artemis v${project.version}
```
**TESTED WITH MULTIPLY FORKS AND PAPER**

**Comment by NoJokeFNA** [comment]
Isn't it more logical to create one single issue for each issue you encounter? It's a mes otherwise.
